"""empty message

Revision ID: 2fd04570fe54
Revises: df1692a0837
Create Date: 2018-02-03 22:21:40.164425

"""

# revision identifiers, used by Alembic.
revision = '2fd04570fe54'
down_revision = 'df1692a0837'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'status',
                    existing_type=sa.VARCHAR(length=10),
                    type_=sa.VARCHAR(length=50))
    op.alter_column('property', 'status',
                    existing_type=sa.VARCHAR(length=10),
                    type_=sa.VARCHAR(length=50))
    # op.execute('ALTER TABLE project ALTER COLUMN status TYPE varchar(50);')
    # op.execute('ALTER TABLE property ALTER COLUMN status TYPE varchar(50);')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.VARCHAR(length=10))
    op.alter_column('property', 'status',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.VARCHAR(length=10))
    # op.execute('ALTER TABLE project ALTER COLUMN status TYPE varchar(10);')
    # op.execute('ALTER TABLE property ALTER COLUMN status TYPE varchar(10);')
    ### end Alembic commands ###
